name: development-test
on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]
defaults:
  run:
    shell: pwsh -command ". '{0}'"
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-11.0]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install protoc 3.13.0 (Linux)
        if: ${{ runner.os == 'Linux' }}
        shell: bash
        run: |
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.13.0/protoc-3.13.0-linux-x86_64.zip
          unzip protoc-3.13.0-linux-x86_64.zip -d $HOME/.local
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install latest protoc (macOS)
        if: ${{ runner.os == 'macOS' }}
        run: brew install protobuf
      - name: Install FPC 3.2.0 (Linux)
        if: ${{ runner.os == 'Linux' }}
        shell: bash
        run: |
          curl -LO http://launchpadlibrarian.net/494661083/fp-units-rtl-3.2.0_3.2.0+dfsg-8build2_amd64.deb
          sudo dpkg -i fp-units-rtl-3.2.0_3.2.0+dfsg-8build2_amd64.deb
          curl -LO http://launchpadlibrarian.net/494661053/fp-compiler-3.2.0_3.2.0+dfsg-8build2_amd64.deb
          sudo dpkg -i fp-compiler-3.2.0_3.2.0+dfsg-8build2_amd64.deb
      - name: Install latest FPC (macOS)
        if: ${{ runner.os == 'macOS' }}
        run: brew install fpc
      - uses: actions/checkout@v2
      - name: Test package stability
        env:
          Work_Connor_Delphi_ProtocGenDelphi_RuntimeTests_SkipDcc64: 1
        run: ./script/github-actions-test.ps1
